[package]
name = "system_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["canvas", "tokio", "debug"] }
sysinfo = "0.30"
tokio = { version = "1", features = ["full"] }
